<div class="row">
	<div class="header-link col-md-7">
		<table class="header-table">
			<tr>
				<td><a href="#"><?= /* @escapeNotVerified */ __('Help') ?></a></td>
				<td class="width"><a href="#"><?= /* @escapeNotVerified */ __('Contact') ?></a></td>
				<td><a href="#"><?= /* @escapeNotVerified */ __('Delivery Information') ?></a></td>
			</tr>
		</table>
	</div>
    <div class="call col-md-5">
        <span><img class="header-call" src="<?php echo $this->getViewFileUrl("images/header-call.png");?>"/><?= /* @escapeNotVerified */ __('Call us : 032 2352 782') ?></span>
    </div>
</div>
<!-- > -->